target: genQC.pipeline.diffusion_pipeline_special.DiffusionPipeline_Compilation
params:
  scheduler:
    target: genQC.scheduler.scheduler_ddim.DDIMScheduler
    params:
      device: cpu
      num_train_timesteps: 1000
      beta_start: 0.0001
      beta_end: 0.02
      beta_schedule: cos_alpha
      input_perturbation: 0.1
      eta: 1
  model:
    target: genQC.models.unet_qc.QC_Compilation_UNet
    save_path: null
    params:
      model_features:
      - 128
      - 128
      - 256
      clr_dim: 8
      num_clrs: 8
      t_emb_size: 256
      cond_emb_size: 512
      num_heads: 
      - 8
      - 8
      - 2
      num_res_blocks: 
      - 2
      - 2
      - 4
      transformer_depths:
      - 1
      - 2
      - 1
      unitary_encoder_config:
        cond_emb_size: 512
        model_features:
        - 2
        - 32
        - 64
        - 512
        num_heads: 8
        transformer_depths:
        - 2
        - 2
        dropout: 0.2
  text_encoder:
    target: genQC.models.frozen_open_clip.CachedFrozenOpenCLIPEmbedder
    save_path: null
    params:
      arch: ViT-B-32
      version: laion2b_s34b_b79k
      device: cpu
      max_length: 77
      freeze: true
      layer: penultimate
  device: cpu
  enable_guidance_train: true
  guidance_train_p: 0.1
  cached_text_enc: true
  add_config:
    dataset:
      params:
        num_of_qubits: 3
        min_gates: 2
        max_gates: 12
        gate_pool:
        - h
        - cx
        - z
        - x
        - ccx
        - swap
        pad_constant: 7

