# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/genQC',
                'doc_host': 'https://FlorianFuerrutter.github.io',
                'git_url': 'https://github.com/FlorianFuerrutter/genQC',
                'lib_path': 'genQC'},
  'syms': {'genQC.imports': {}}}
