name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
env:
  OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: answerdotai/workflows/quarto-ghp@master
        with:
          version: "3.12"